version: "3"
services:
  server:
    image: backend
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/employeedb?useSSL=false
    networks:
      - springmysql-net
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:5.7
    networks:
      - springmysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=Farah@99
      - MYSQL_DATABASE=employeedb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Farah@99

networks:
  springmysql-net:
